name: little_birds
description: A new Flutter application.

version: 1.1.3+19091500

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.12.0+2
  flutter_html: ^0.10.4
  timeago: ^2.0.18
  keyboard_visibility: any
  photo_view: ^0.4.2
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.1
  firebase_crashlytics: ^0.1.0+3
  firebase_admob: ^0.9.0+7
  url_launcher: ^5.1.3
  uni_links: ^0.2.0
  flutter_secure_storage: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/launcher/icon.png"
  image_path_android: "assets/launcher/icon.png"